# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script: 
    - mysql -e 'create database IF NOT EXISTS mcc_fundraise'
    #phpenv config-add dnsconfig.php  
	